FROM node:16.14.0-alpine
# Also exposing VSCode debug ports
EXPOSE 8000 9929 9930

RUN \
  apk add --no-cache python3 make g++ && \
  apk add vips-dev fftw-dev --update-cache \
  --repository http://dl-3.alpinelinux.org/alpine/edge/community \
  --repository http://dl-3.alpinelinux.org/alpine/edge/main \
 && rm -fR /var/cache/apk/*

RUN apk add automake autoconf libtool nasm

RUN npm install -g gatsby-cli

WORKDIR /app
COPY ./package.json .
RUN npm install
COPY . .
CMD ["gatsby", "develop", "-H", "0.0.0.0" ]